### ISSUE TITLE
Add deeper configuration

### ISSUE THREAD

**Issue by PedroTroller** [KnpLabs/rad-auto-registration#36]
Example : 

``` yaml
knp_rad_auto_registration:
    enable:
        doctrine:
            public: true
        twig_extension:
            public: false # default config
```
